CREATE TABLE `category`(
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `category` VARCHAR(50),
    PRIMARY KEY (`id`)
);

INSERT INTO `category` (`id`, `category`) VALUES (1, 'Blog de Gaea'), (2, 'Noob'), (3, 'Flanders Company');

CREATE TABLE `product` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(225) DEFAULT NULL,
    `price` float DEFAULT NULL,
    `stock` int(11) DEFAULT NULL,
    `short_description` text,
    `long_description` text,
    `id_category` int(11) NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`id_category`) REFERENCES `category`(`id`)
);

INSERT INTO `product` (`id`, `name`, `price`, `stock`, `short_description`, `long_description`, `id_category`) VALUES
(1, 'BD 1 Blog de Gaea : La bourse ou la vie in game', 13.5, 35, 'Gabrielle Jolivet a beau collectionner avidement les crédits lorsqu\'elle joue son personnage de Gaea l\'invocatrice dans son jeu vidéo en ligne préféré, elle n\'en reste pas moins sans le sou.\r\n\r\n', 'Gabrielle Jolivet a beau collectionner avidement les crédits lorsqu\'elle joue son personnage de Gaea l\'invocatrice dans son jeu vidéo en ligne préféré, elle n\'en reste pas moins sans le sou, comme la plupart des étudiants de son âge. Manipulatrice vénale pour certains, ingénieuse et économe pour d\'autres, c\'est sur son blog qu\'elle sévit. Suivez ses aventures et celles de ses amis dans sa quête du buzz !\r\n\r\nScénario : Anne-Laure Jarnet\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Olydri édition\r\n\r\nFormat BD franco-belge : 48 pages', 1),
(2, 'BD 2 Blog de Gaea : Au nom de la loi !', 13.5, 15, 'Gabrielle Jolivet, alias Gaea, est membre de la guilde Noob, qui rassemble des amateurs de jeux vidéo en ligne. ', 'Gabrielle Jolivet, alias Gaea, est membre de la guilde Noob, qui rassemble des amateurs de jeux vidéo en ligne. Elle est toujours à la recherche d\'idées pour alimenter le blog qu\'elle a créé. Une série tirée de sketchs vidéo diffusés sur Internet, qui raconte la vie quotidienne de la communauté geek.\r\n\r\nScénario : Anne-Laure Jarnet\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Olydri édition\r\n\r\nFormat BD franco-belge : 48 pages ', 1),
(3, 'BD 3 Blog de Gaea : Horizon lointain', 13.5, 14, 'Vous allez suivre toute la bande, emportés par la quête du buzz de Gabrielle Jolivet et son blog.', 'Gabrielle Jolivet a beau collectionner avidement les crédits lorsqu’elle joue son personnage de Gaea l’invocatrice dans son jeu vidéo en ligne préféré, elle n’en reste pas moins sans le sou, comme la plupart des étudiants de son âge. Manipulatrice vénale pour certains, ingénieuse et économe pour d’autres, c’est sur son blog qu’elle sévit. Suivez ses aventures et celles de ses amis dans sa quête du buzz !\r\nLa bande dessinée du Blog de Gaea s\'inscrit dans l\'univers étendu de Noob. Pour faire simple, il s\'agit de l\'aventure vécue par les héros de Noob, quand ils ne jouent pas à Horizon 1.0. Que font-ils dans le monde réel ? Qui connaît qui ? Quels sont leurs problèmes ? Vous allez suivre toute la bande, emportés par la quête du buzz de Gabrielle Jolivet et son blog.\r\n\r\nScénario : Anne-Laure Jarnet\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Olydri édition\r\n\r\nFormat BD franco-belge : 48 pages ', 1),
(4, 'BD 4 Blog de Gaea : Une journée en concert', 13.5, 10, 'Que font les membres de la guilde Noob quand ils ne jouent pas aux jeux vidéo en ligne ? ', 'Que font les membres de la guilde Noob quand ils ne jouent pas aux jeux vidéo en ligne ? Quelles sont leurs occupations etpréoccupations dans la vie de tous les jours ?Découvrez le monde geek d\'aujourd\'hui à travers les aventures de Gabrielle Jolivet alias Gaea, à la recherche du buzz pour son blog !Le blog de Gae@ est à la fois une aventure 100% indépendante tirée d\'une série de sketchs vidéos du même nom (400 000 vues par épisodes) et un spinoff offi ciel de Noob !\r\n\r\nScénario : Anne-Laure Jarnet\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Olydri édition\r\n\r\nFormat BD franco-belge : 48 pages ', 2),
(5, 'BD 1 Noob : Tu veux entrer dans ma guilde', 10.85, 14, 'Suivez les aventures d\'Arthéon le guerrier, chef de la désastreuse guilde Noob, Gaea l\'invocatrice, manipulatrice et vénale, Omega Zell l\'assassin, macho et égocentrique, sans oublier le pire de tous, Sparadrap le prêtre, naïf et simplet. ', 'Suivez les aventures d\'Arthéon le guerrier, chef de la désastreuse guilde Noob, Gaea l\'invocatrice, manipulatrice et vénale, Omega Zell l\'assassin, macho et égocentrique, sans oublier le pire de tous, Sparadrap le prêtre, naïf et simplet. Ils devront se supporter pour accomplir de nombreuses quêtes, explorer des donjons, parcourir des régions et affronter de terribles monstres pour passer de niveaux en niveaux.\r\n\r\nScénario : Fabien Fournier\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Soleil\r\n\r\nFormat BD franco-belge : 40 pages ', 2),
(6, 'BD 2 Noob : Les filles elles savent jouer', 10.85, 25, 'Omega Zell, l\'assassin, estime que les filles ne savent pas jouer, ce qui déplaît fortement à Gaea l\'invocatrice, prompte à défendre la cause féminine virtuelle. ', 'Omega Zell, l\'assassin, estime que les filles ne savent pas jouer, ce qui déplaît fortement à Gaea l\'invocatrice, prompte à défendre la cause féminine virtuelle. Pendant que ces derniers se disputent, Sparadrap le prêtre, peine à rester concentré, et ne soigne pas ses compagnons au grand dam d\'Arthéon le guerrier, qui doit chaperonner tout ce petit monde dans l\'espoir de faire avancer sa guilde !\r\n\r\nScénario : Fabien Fournier\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Soleil\r\n\r\nFormat BD franco-belge : 40 pages ', 2),
(7, 'BD 3 Noob : Un jour je serai niveau 100', 10.85, 14, 'Arthéon tente désespérément de mener ses compagnons jusqu\'au très convoité niveau 100. Une tâche difficile lorsqu\'on doit gérer la désastreuse guilde Noob. ', 'Arthéon tente désespérément de mener ses compagnons jusqu\'au très convoité niveau 100. Une tâche difficile lorsqu\'on doit gérer la désastreuse guilde Noob. Dans ce jeu basé sur la cohabitation entre joueurs, ils devront se supporter pour accomplir de nombreuses quêtes. Une affaire bien mal embarquée...\r\n\r\nScénario : Fabien Fournier\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Soleil\r\n\r\nFormat BD franco-belge : 40 pages ', 2),
(8, 'BD 4 Noob : Les crédits ou la vie', 10.85, 24, 'Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri, et vivent des aventures épiques sans bouger de leur fauteuil. ', 'Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri, et vivent des aventures épiques sans bouger de leur fauteuil. Au milieu de ce petit monde, la désastreuse guilde Noob tente de se frayer un chemin vers le très convoité niveau cent ! Une affaire bien mal embarquée pour Arthéon le guerrier et ses compagnons d\'infortune, qui voient la terrible tour Galamadriabuyak se dresser sur leur route. Si Sparadrap, Gaea, Omega Zell et Arthéon veulent sortir victorieux du plus célèbre donjon d\'Olydri, ils vont devoir faire preuve de solidarité, de discipline et de dextérité ! Ce serait bien la première fois.\r\n\r\nScénario : Fabien Fournier\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Soleil\r\n\r\nFormat BD franco-belge : 40 pages ', 2),
(9, 'BD 5 Noob : La coupe de Fluxball', 10.85, 23, 'Bien mal embarquée dans sa quête du niveau 100, la guilde Noob a l\'occasion de souffler un peu avec l\'arrivée de la mise à jour 1.3, mettant en place un sport déjanté appelé Fluxball.', 'Bien mal embarquée dans sa quête du niveau 100, la guilde Noob a l\'occasion de souffler un peu avec l\'arrivée de la mise à jour 1.3, mettant en place un sport déjanté appelé Fluxball.Pour une fois, Sparadrap, Gaea, Omega Zell et Arthéon croient en leurs chances de mettre la main sur la récompense promise aux futurs vainqueurs de la coupe. Hélas, ils vont très vite déchanter en apprenant l\'alliance entre les deux meilleurs joueurs du jeu, au sein d\'une équipe annoncée comme invincible.\r\n\r\nScénario : Fabien Fournier\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Soleil\r\n\r\nFormat BD franco-belge : 40 pages ', 2),
(10, 'BD 6 Noob : Désordre en Olydri', 10.85, 14, 'Bien mal embarquée dans sa quête du niveau 100, la guilde Noob voit sa tâche s’alourdir encore un peu plus avec la sortie d’une nouvelle extension, et toutes les quêtes, ennemis et autres donjons inédits que cela implique. ', 'Bien mal embarquée dans sa quête du niveau 100, la guilde Noob voit sa tâche s’alourdir encore un peu plus avec la sortie d’une nouvelle extension, et toutes les quêtes, ennemis et autres donjons inédits que cela implique. Alors imaginez si en plus de tout cela, Tenshirock, le pirate informatique, venait à refaire surface pour fausser la donne. Ce serait vraiment le pompon…\r\n\r\nScénario : Fabien Fournier\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Soleil\r\n\r\nFormat BD franco-belge : 40 pages ', 2),
(11, 'BD 7 Noob : La chute de l\'empire', 10.85, 12, 'Horizon 2.0 est un jeu vidéo en ligne à la mode. Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri, et vivent des aventures épiques sans bouger de leur fauteuil. ', 'Horizon 2.0 est un jeu vidéo en ligne à la mode. Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri, et vivent des aventures épiques sans bouger de leur fauteuil. Arthéon et ses amis, déjà laborieux dans leur progression vers le niveau 100, voient leur tâche s\'alourdir encore un peu plus avec l\'arrivée de l\'Ordre, la troisième faction devenue jouable, mais aussi le retour d\'une vieille connaissance, bien décidée à leur en faire baver ! Le danger est partout ! Dans le monde réel et dans le jeu ! L\'avenir de la guilde Noob n\'a jamais été aussi sombre.\r\n\r\nScénario : Fabien Fournier\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Soleil\r\n\r\nFormat BD franco-belge : 40 pages ', 2),
(12, 'BD 8 Noob : Retour à la case départ', 10.85, 2, 'Horizon 2.0 est un jeu vidéo en ligne à la mode. Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri, et vivent des aventures épiques sans bouger de leur fauteuil. ', 'Horizon 2.0 est un jeu vidéo en ligne à la mode. Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri, et vivent des aventures épiques sans bouger de leur fauteuil. Arthéon et ses amis, déjà laborieux dans leur progression vers le niveau 100, voient leur tâche s\'alourdir encore un peu plus avec l\'arrivée de Fantöm dans leurs rangs ! Malgré ses efforts, l\'ancien champion de la guilde Justice, affublé d\'un avatar de retour à la case départ, peine à ne pas faire office de boulet. Fantöm retrouvera-t-il son niveau d\'antan et portera-t-il la guilde Noob vers un triomphe inespéré ? Pour cela, il faudra d\'abord se débarrasser de ses nombreux ennemis qui n\'attendent qu\'une chose. se venger !\r\nScénario : Fabien Fournier\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Soleil\r\n\r\nFormat BD franco-belge : 46 pages \r\n', 2),
(13, 'BD 9 Noob : Mauvaise réputation', 10.85, 1, 'Horizon 2.0 est un jeu vidéo en ligne à la mode. Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri, et vivent des aventures épiques sans bouger de leur fauteuil. ', 'Horizon 2.0 est un jeu vidéo en ligne à la mode. Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri, et vivent des aventures épiques sans bouger de leur fauteuil. Arthéon et ses amis, déjà laborieux dans leur progression vers le niveau 100, voient leur tâche s\'alourdir encore un peu plus avec la manifestation d\'un étrange phénomène. Tous les personnages non joueurs semblent leur en vouloir, au point de les rejeter où qu\'ils aillent et quoi qu\'ils fassent. La guilde Noob va se rendre compte que ce revirement de comportement, au sein de leur propre faction, est dû à une accumulation de gaffes de leur part. Leurs points de réputation sont désormais au plus bas, et il va falloir y remédier ! Peut-être en s\'enrôlant dans l\'armée, et en participant à des champs de bataille, qui sait ?\r\n\r\nScénario : Fabien Fournier\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Soleil\r\n\r\nFormat BD franco-belge : 46 pages ', 2),
(14, 'BD 10 Noob : A la guerre comme à la guerre !', 10.85, 4, ' Horizon 2.0 est un jeu vidéo en ligne qui fait fureur. Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri et vivent des aventures épiques sans bouger de leur fauteuil. Arthéon et ses amis.', 'Horizon 2.0 est un jeu vidéo en ligne qui fait fureur. Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri et vivent des aventures épiques sans bouger de leur fauteuil. Arthéon et ses amis, toujours en quête du sacro-saint niveau 100, redoutent de voir leurs efforts réduits à néant dans les prochains jours, car leur faction est sur le point d\'être rayée de la carte. Depuis la chute de Fantöm, les joueurs de l\'Empire, dépités, ont déserté massivement le jeu, laissant la voie libre à la Coalition, leur ennemi juré. La situation est si désespérée que même la guilde Noob, fidèle au poste en dépit de ces temps difficiles, pourrait bien avoir un rôle à jouer, aussi infime soit-il...\r\n\r\nScénario : Fabien Fournier\r\nDessin : Philippe Cardona\r\nCouleurs : Florence Torta\r\nEdition : Soleil\r\n\r\nFormat BD franco-belge : 46 pages ', 2),
(15, 'BD 11 Noob : Trois factions, trois champions, une légende !', 10.85, 4, 'Horizon 2.0 est un jeu vidéo en ligne à la mode. Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri et vivent des aventures épiques sans bouger de leur fauteuil. ', 'Horizon 2.0 est un jeu vidéo en ligne à la mode. Chaque jour, des millions de joueurs arpentent le monde virtuel d\'Olydri et vivent des aventures épiques sans bouger de leur fauteuil. Arthéon et ses amis, toujours en quête du sacro-saint niveau 100, redoutent de voir leurs efforts réduits à néant dans les prochains jours, car leur faction est sur le point d\'être rayée de la carte. Depuis la chute de Fantöm, les joueurs de l\'Empire, dépités, ont déserté massivement le jeu, laissant la voie libre à la Coalition, leurs ennemis jurés. La situation est si désespérée que même la guilde Noob, fidèle au poste en dépit de ces temps difficiles, pourrait bien avoir un rôle à jouer, aussi infime soit-il...', 2),
(16, 'BD 12 Noob : Le tournoi des espoirs', 10.85, 1, 'En tant que championne de fluxball, la guilde Noob est conviée pour la première fois à la coupe du monde de E-sport.', ' En tant que championne de fluxball, la guilde Noob est conviée pour la première fois à la coupe du monde de E-sport, pour concourir dans la catégorie Espoirs. Une occasion unique d\'attirer l\'attention des sponsors et de passer professionnels, à l\'image des superstars des guildes Justice et Roxor. Arthéon et ses amis s\'envolent donc pour Tokyo, la ville organisatrice, qu\'ils vont découvrir d\'une manière inattendue...', 2),
(17, 'BD 13 Noob : La capture d\'écran', 10.85, 14, 'Après des années de quêtes, de donjons, et de champs de bataille, la guilde Noob n\'a jamais été aussi proche d\'atteindre enfin le « niveau 100 », le Saint Graal de tout joueur de jeu vidéo en ligne !', 'Après des années de quêtes, de donjons, et de champs de bataille, la guilde Noob n\'a jamais été aussi proche d\'atteindre enfin le « niveau 100 », le Saint Graal de tout joueur de jeu vidéo en ligne ! Pour y prétendre, ils vont d\'abord devoir terminer le neuvième étage de la tour Galamadriabuyak. Pour triompher, ils pourront compter sur un allié de poids ! Fantöm, le champion déchu, accepte de leur apporter son aide une dernière fois, avant que sa propre destinée ne le rattrape.', 2),
(18, 'BD 1 Flander\'s Company : Ils servent le mal et ils le servent bien', 11, 14, 'Série télévisée adaptée en bande dessinée. La Flander\'s Company forme et assure le support logistique des super-vilains d\'aujourd\'hui et de demain.', ' Que seraient les super-héros s’ils n’avaient pas de super-vilains à combattre ? Sûrement pas les stars planétaires adulées des foules que l’on connaît aujourd’hui. Non, sans une Némésis crédible, le super-héros n’est pas grand chose de plus qu’un simple représentant de l’ordre aux goûts vestimentaires douteux.\r\nHeureusement, il y a la Flander’s Company ! Cette entreprise recrute et forme les pires des vilains - la crème de la crème - avant de louer leurs services à tous les justiciers en manque de renommée. Alors certes, le patron est tyrannique, ses employés un brin loufoques, les tarifs pratiqués totalement exhorbitants… mais tout ce qui compte, finalement, c’est qu’ils servent le Mal. Et ils le servent sacrément bien !', 3),
(19, 'BD 2 Flander\'s Company : Le mal, c\'est classe !', 11, 25, 'Série télévisée adaptée en bande dessinée. La Flander\'s Company forme et assure le support logistique des super-vilains d\'aujourd\'hui et de demain.', 'Bienvenue à la Flander\'s Company, cette formidable entreprise qui recrute, forme et assure un support logistique et moral à la crème des Super Vilains d\'aujourd\'hui et de demain ! Nous faisons le mal et nous le faisons bien !', 3),
(20, 'BD 3 Flander\'s Company : Le mal s\'habille en Chantal !', 11, 5, 'Armand Trueman a été viré ! Victime d\'une OPA agressive fomentée par l\'égérie vieillissante de la mode, Chantal Connasse, le PDG à la mèche soyeuse a vu la Flander\'s Company lui échapper des mains. Hippolyte, Caleb et Cindy doivent désormais composer avec une nouvelle direction présidée par la terrible Carla Burnelle. Sous le choc, nos Super Vilains préférés n\'ont pas encore eu l\'occasion de réfléchir à une contre-attaque en bonne et due forme. Mais cela ne saurait trop tarder...', 'La Flander\'s Company est une entreprise atypique qui recrute, forme et équipe les pires des génies du mal - les super-vilains - avant de louer leurs services sous forme de combats truqués à tous les justiciers en manque de renommée et de scrupules. Elle est menée d\'une main de fer par son PDG Armand Trueman et son équipe dont la bd relate les aventures quotidiennes.', 3);


